language: php

php:
  - 7.3
  - 7.4
  - 8.0

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SYMFONY_VERSION=5.3.*
    - php: 7.4
      env: SYMFONY_VERSION=5.3.*
    - php: 8.0
      env: SYMFONY_VERSION=5.3.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mkdir -p build/logs
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
